# Generated by Django 2.2.3 on 2019-07-25 17:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApendiceCabecera',
            fields=[
                ('ID_APENDICE', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('DES_APENDICE', models.CharField(blank=True, max_length=100, null=True)),
                ('FECHA_INICIO', models.DateTimeField(blank=True, null=True)),
                ('FECHA_FIN', models.DateTimeField(blank=True, null=True)),
                ('FINALIZADO', models.BinaryField(blank=True, null=True)),
                ('FECHA_FIN_OC_CLIENTE', models.DateTimeField(blank=True, null=True)),
                ('COMENTARIO', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'apendice_cabecera',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ID_CLIENTE', models.AutoField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('FECHA_ALTA', models.DateTimeField(blank=True, null=True)),
                ('NUM_CLIENTE_PROV', models.CharField(blank=True, max_length=20, null=True)),
                ('NUM_CLIENTE_PLNG', models.CharField(blank=True, max_length=20, null=True)),
                ('COMENTARIOS', models.CharField(blank=True, max_length=200, null=True)),
                ('RAZON_SOCIAL', models.CharField(blank=True, max_length=50, null=True)),
                ('CLAVE_FISCAL', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('ID_CONTACTO', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('NOMBRE_CONTACTO', models.CharField(blank=True, max_length=40)),
                ('MAIL', models.CharField(blank=True, max_length=50)),
                ('TELEFONO', models.CharField(blank=True, max_length=20)),
                ('DOMICILIO', models.CharField(blank=True, max_length=100, null=True)),
                ('CP', models.CharField(blank=True, max_length=20, null=True)),
                ('CIUDAD', models.CharField(blank=True, max_length=30, null=True)),
                ('PROVINCIA', models.CharField(blank=True, max_length=30, null=True)),
                ('PAIS', models.CharField(blank=True, max_length=20, null=True)),
                ('PRIORIDAD', models.IntegerField(blank=True, max_length=11, null=True)),
                ('ID_CLIENTE', models.ForeignKey(db_column='ID_CLIENTE', on_delete=django.db.models.deletion.CASCADE, to='main.Cliente')),
            ],
            options={
                'db_table': 'contacto',
            },
        ),
        migrations.CreateModel(
            name='ContractsModel',
            fields=[
                ('id', models.AutoField(help_text='user Id', max_length=11, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, help_text='username', max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, help_text='first name', max_length=30)),
                ('last_name', models.CharField(blank=True, help_text='last name', max_length=150)),
                ('email', models.CharField(blank=True, help_text='email', max_length=254)),
                ('is_superuser', models.SmallIntegerField(blank=True, help_text='check superuser', max_length=1, null=True)),
            ],
            options={
                'db_table': 'myauth',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContratoCabecera',
            fields=[
                ('ID_CONTRATO', models.AutoField(help_text='ID of Contrato', max_length=15, primary_key=True, serialize=False)),
                ('FECHA_FIRMA', models.DateTimeField(blank=True, null=True)),
                ('FECHA_INICIO', models.DateTimeField(blank=True, null=True)),
                ('FECHA_FIN', models.DateTimeField(blank=True, null=True)),
                ('FINALIZADO', models.BinaryField(blank=True, null=True)),
                ('COMENTARIO', models.CharField(blank=True, max_length=500, null=True)),
                ('ID_CLIENTE', models.ForeignKey(db_column='ID_CLIENTE', on_delete=django.db.models.deletion.CASCADE, to='main.Cliente')),
                ('ID_CONTACTO', models.ForeignKey(db_column='ID_CONTACTO', on_delete=django.db.models.deletion.CASCADE, to='main.Contacto')),
            ],
            options={
                'db_table': 'contrato_cabecera',
            },
        ),
        migrations.CreateModel(
            name='CuotaPo',
            fields=[
                ('ID_CUOTA', models.IntegerField(help_text='Id of Couta', max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('FECHA_VENCIMIENTO', models.DateTimeField(blank=True, null=True)),
                ('NRO_FACTURA', models.IntegerField(blank=True, max_length=11, null=True)),
                ('SOCIEDAD', models.BinaryField(blank=True, null=True)),
                ('FECHA_FACTURA', models.DateTimeField(blank=True, null=True)),
                ('MONTO', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('COBRADA', models.BinaryField(blank=True, null=True)),
                ('ID_CLIENTE', models.ForeignKey(db_column='ID_CLIENTE', on_delete=django.db.models.deletion.CASCADE, to='main.Cliente')),
            ],
            options={
                'db_table': 'cuota_po',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('ID_ESTADO', models.AutoField(help_text='ID_ESTADO', max_length=11, primary_key=True, serialize=False)),
                ('COD_ESTADO', models.CharField(blank=True, help_text='COD_ESTADO', max_length=10, null=True)),
                ('DES_ESTADO', models.CharField(blank=True, help_text='DES_ESTADO', max_length=50, null=True)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='GrupoCliente',
            fields=[
                ('ID_INDUSTRIA2', models.AutoField(help_text='ID_INDUSTRIA2', max_length=11, primary_key=True, serialize=False)),
                ('COD_GRUPO_CLIENTE', models.CharField(blank=True, help_text='COD_GRUPO_CLIENTE', max_length=100, null=True)),
                ('DES_GRUPO_CLIENTE', models.CharField(blank=True, help_text='DES_GRUPO_CLIENTE', max_length=100, null=True)),
            ],
            options={
                'db_table': 'grupo_cliente',
            },
        ),
        migrations.CreateModel(
            name='Industria',
            fields=[
                ('ID_INDUSTRIA', models.AutoField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('COD_INDUSTRIA', models.CharField(blank=True, max_length=10, null=True)),
                ('DES_INDUSTRIA', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'industria',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('ID_PAIS', models.AutoField(help_text='ID of Pais', max_length=11, primary_key=True, serialize=False)),
                ('COD_PAIS', models.CharField(blank=True, help_text='Cod of pais', max_length=3, null=True)),
                ('DES_PAIS', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'pais',
            },
        ),
        migrations.CreateModel(
            name='Po',
            fields=[
                ('ID_PO', models.AutoField(help_text='Id of Po', max_length=11, primary_key=True, serialize=False)),
                ('FECHA_PO', models.DateTimeField(blank=True, null=True)),
                ('MONTO_COSTO', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('MONTO_CLIENTE', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('MONTO_MARGEN', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('COMENTARIO', models.CharField(blank=True, max_length=500, null=True)),
                ('ID_APENDICE', models.ForeignKey(db_column='ID_APENDICE', on_delete=django.db.models.deletion.CASCADE, to='main.ApendiceCabecera')),
                ('ID_CLIENTE', models.ForeignKey(db_column='ID_CLIENTE', on_delete=django.db.models.deletion.CASCADE, to='main.Cliente')),
                ('ID_CONTACTO', models.ForeignKey(db_column='ID_CONTACTO', on_delete=django.db.models.deletion.CASCADE, to='main.Contacto')),
                ('ID_CONTRATO', models.ForeignKey(db_column='ID_CONTRATO', on_delete=django.db.models.deletion.CASCADE, to='main.ContratoCabecera')),
            ],
            options={
                'db_table': 'po',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('ID_REGION', models.AutoField(help_text='ID of Pais', max_length=11, primary_key=True, serialize=False)),
                ('COD_REGION', models.CharField(blank=True, help_text='Cod of pais', max_length=10, null=True)),
                ('DES_REGION', models.CharField(blank=True, help_text='DES_REGION', max_length=100, null=True)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Sociedad',
            fields=[
                ('ID_SOCIEDAD', models.AutoField(help_text='ID_SOCIEDAD', max_length=11, primary_key=True, serialize=False)),
                ('RAZON_SOCIAL', models.CharField(blank=True, help_text='RAZON_SOCIAL', max_length=50, null=True)),
                ('CLAVE_FISCAL', models.CharField(blank=True, help_text='CLAVE_FISCAL', max_length=50, null=True)),
            ],
            options={
                'db_table': 'sociedad',
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('ID_TIPO_CONTRATO', models.AutoField(help_text='ID_TIPO_CONTRATO', max_length=11, primary_key=True, serialize=False)),
                ('COD_TIPO_CONTRATO', models.CharField(blank=True, help_text='COD_TIPO_CONTRATO', max_length=100, null=True)),
                ('DES_TIPO_CONTRATO', models.CharField(blank=True, help_text='DES__TIPO_CONTRATO', max_length=100, null=True)),
            ],
            options={
                'db_table': 'tipo_contrato',
            },
        ),
        migrations.CreateModel(
            name='TipoPosicion',
            fields=[
                ('ID_TIPO_POSICION', models.AutoField(help_text='ID_TIPO_POSICION', max_length=11, primary_key=True, serialize=False)),
                ('COD_TIPO_POSICION', models.CharField(blank=True, help_text='COD_TIPO_POSICION', max_length=50, null=True)),
                ('DES_TIPO_POSICION', models.CharField(blank=True, help_text='DES_TIPO_POSICION', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tipo_posicion',
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('ID_TIPO_PRODUCTO', models.AutoField(help_text='ID_TIPO_PRODUCTO', max_length=11, primary_key=True, serialize=False)),
                ('COD_TIPO_PRODUCTO', models.CharField(blank=True, help_text='COD_TIPO_PRODUCTO', max_length=50, null=True)),
                ('DES_TIPO_PRODUCTO', models.CharField(blank=True, help_text='DES_TIPO_PRODUCTO', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tipo_producto',
            },
        ),
        migrations.CreateModel(
            name='UnidadNegocio',
            fields=[
                ('ID_UNIDAD_NEGOCIO', models.AutoField(help_text='ID_UNIDAD_NEGOCIO', max_length=11, primary_key=True, serialize=False)),
                ('COD_UNIDAD_NEGOCIO', models.CharField(blank=True, help_text='COD_UNIDAD_NEGOCIO', max_length=50, null=True)),
                ('DES_UNIDAD_NEGOCIO', models.CharField(blank=True, help_text='DES_UNIDAD_NEGOCIO', max_length=50, null=True)),
            ],
            options={
                'db_table': 'unidad_negocio',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('ID_VENDEDOR', models.AutoField(help_text='ID_VENDEDOR', max_length=11, primary_key=True, serialize=False)),
                ('APELLIDO_VENEDOR', models.CharField(blank=True, help_text='APELLIDO_VENEDOR', max_length=50, null=True)),
                ('NOMBRE_VENDEDOR', models.CharField(blank=True, help_text='NOMBRE_VENDEDOR', max_length=50, null=True)),
                ('INICIALES_VENEDOR', models.CharField(blank=True, help_text='INICIALES_VENEDOR', max_length=3, null=True)),
            ],
            options={
                'db_table': 'vendedor',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('ID_PROVEEDOR', models.AutoField(help_text='Id of Proveedor', max_length=11, primary_key=True, serialize=False)),
                ('COD_PROVEEDOR', models.CharField(blank=True, max_length=10, null=True)),
                ('DES_PROVEEDOR', models.CharField(blank=True, max_length=100, null=True)),
                ('CLAVE_FISCAL', models.CharField(blank=True, max_length=50, null=True)),
                ('RAZON_SOCIAL', models.CharField(blank=True, max_length=50, null=True)),
                ('NOMBRE_FANTASIA', models.CharField(blank=True, max_length=50, null=True)),
                ('DIRECCION', models.CharField(blank=True, max_length=50, null=True)),
                ('PAIS', models.CharField(blank=True, max_length=20, null=True)),
                ('ID_UNIDAD_NEGOCIO', models.ForeignKey(db_column='ID_UNIDAD_NEGOCIO', on_delete=django.db.models.deletion.CASCADE, to='main.UnidadNegocio')),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ID_PRODUCTO', models.AutoField(help_text='Id of Producto', max_length=11, primary_key=True, serialize=False)),
                ('COD_PRODUCTO', models.CharField(blank=True, max_length=10)),
                ('DES_PRODUCTO', models.CharField(blank=True, max_length=100)),
                ('METRICA', models.CharField(blank=True, max_length=20, null=True)),
                ('BLOQUES', models.IntegerField(blank=True, max_length=11, null=True)),
                ('MINIMO', models.IntegerField(blank=True, max_length=11, null=True)),
                ('ID_TIPO_PRODUCTO', models.ForeignKey(db_column='ID_TIPO_PRODUCTO', on_delete=django.db.models.deletion.CASCADE, to='main.TipoProducto')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='PoDetalle',
            fields=[
                ('ID_POSICION', models.IntegerField(help_text='Id of Posicion', max_length=11, primary_key=True, serialize=False)),
                ('CANTIDAD', models.IntegerField(blank=True, max_length=11, null=True)),
                ('VALOR_UNITARIO', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('TOTAL', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('PORCENTAJE_DTO_CLIENTE', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('VALOR_VENTA', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('PORCENTAJE_DTO_VENDOR', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('COSTO_VENDOR', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('PORCENTAJE_COM_PARTNER', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('COSTO_TOTAL', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('MARGEN', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('ID_PO', models.ForeignKey(db_column='ID_PO', on_delete=django.db.models.deletion.CASCADE, to='main.Po')),
                ('ID_TIPO_POSICION', models.ForeignKey(db_column='ID_TIPO_POSICION', on_delete=django.db.models.deletion.CASCADE, to='main.TipoPosicion')),
            ],
            options={
                'db_table': 'po_detalle',
            },
        ),
        migrations.CreateModel(
            name='FacturaProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FECHA_OBJETIVO', models.DateTimeField(blank=True, null=True)),
                ('FECHA_FACTURA', models.DateTimeField(blank=True, null=True)),
                ('MONTO', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('NRO_FACTURA', models.IntegerField(blank=True, help_text='Id of Couta', max_length=11, null=True)),
                ('PAGADA', models.BinaryField(blank=True, null=True)),
                ('ID_CUOTA', models.ForeignKey(db_column='ID_CUOTA', on_delete=django.db.models.deletion.CASCADE, to='main.CuotaPo')),
                ('ID_PO', models.ForeignKey(db_column='ID_PO', on_delete=django.db.models.deletion.CASCADE, to='main.Po')),
                ('ID_PROVEEDOR', models.ForeignKey(db_column='ID_PROVEEDOR', on_delete=django.db.models.deletion.CASCADE, to='main.Proveedor')),
            ],
            options={
                'db_table': 'factura_proveedor',
            },
        ),
        migrations.CreateModel(
            name='DetalleApendice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_POSICION', models.IntegerField(blank=True, help_text='Id of Posicion', max_length=11)),
                ('CANTIDAD', models.IntegerField(blank=True, max_length=11, null=True)),
                ('VALOR_UNITARIO', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('TOTAL', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('PORCENTAJE_DTO_CLIENTE', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('VALOR_VENTA', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('PORCENTAJE_DTO_VENDOR', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('COSTO_VENDOR', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('PORCENTAJE_COM_PARTNER', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('COSTO_PARTNER', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('COSTO_TOTAL', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('MARGEN', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('COBRADA', models.BinaryField(blank=True, null=True)),
                ('ID_APENDICE', models.ForeignKey(db_column='ID_APENDICE', on_delete=django.db.models.deletion.CASCADE, to='main.ApendiceCabecera')),
                ('ID_PRODUCTO', models.ForeignKey(db_column='ID_PRODUCTO', on_delete=django.db.models.deletion.CASCADE, to='main.Producto')),
                ('ID_TIPO_POSICION', models.ForeignKey(db_column='ID_TIPO_POSICION', on_delete=django.db.models.deletion.CASCADE, to='main.TipoProducto')),
            ],
            options={
                'db_table': 'detalle_apendice',
            },
        ),
        migrations.AddField(
            model_name='cuotapo',
            name='ID_PO',
            field=models.ForeignKey(db_column='ID_PO', on_delete=django.db.models.deletion.CASCADE, to='main.Po'),
        ),
        migrations.AddField(
            model_name='contratocabecera',
            name='ID_INDUSTRIA3',
            field=models.ForeignKey(db_column='ID_INDUSTRIA3', on_delete=django.db.models.deletion.CASCADE, to='main.Industria'),
        ),
        migrations.AddField(
            model_name='contratocabecera',
            name='ID_PROVEEDOR',
            field=models.ForeignKey(db_column='ID_PROVEEDOR', on_delete=django.db.models.deletion.CASCADE, to='main.Proveedor'),
        ),
        migrations.AddField(
            model_name='contratocabecera',
            name='ID_REGION',
            field=models.ForeignKey(db_column='ID_REGION', on_delete=django.db.models.deletion.CASCADE, to='main.Region'),
        ),
        migrations.AddField(
            model_name='contratocabecera',
            name='ID_SOCIEDAD',
            field=models.ForeignKey(db_column='ID_SOCIEDAD', on_delete=django.db.models.deletion.CASCADE, to='main.Sociedad'),
        ),
        migrations.AddField(
            model_name='contratocabecera',
            name='ID_TIPO_CONTRATO',
            field=models.ForeignKey(db_column='ID_TIPO_CONTRATO', on_delete=django.db.models.deletion.CASCADE, to='main.TipoContrato'),
        ),
        migrations.AddField(
            model_name='contratocabecera',
            name='ID_UNIDAD_NEGOCIO',
            field=models.ForeignKey(db_column='ID_UNIDAD_NEGOCIO', on_delete=django.db.models.deletion.CASCADE, to='main.UnidadNegocio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ID_GRUPO_CLIENTE',
            field=models.ForeignKey(db_column='ID_GRUPO_CLIENTE', on_delete=django.db.models.deletion.CASCADE, to='main.GrupoCliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ID_INDUSTRIA',
            field=models.ForeignKey(db_column='ID_INDUSTRIA', on_delete=django.db.models.deletion.CASCADE, to='main.Industria'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ID_PAIS',
            field=models.ForeignKey(db_column='ID_PAIS', on_delete=django.db.models.deletion.CASCADE, to='main.Pais'),
        ),
        migrations.AddField(
            model_name='apendicecabecera',
            name='ID_CONTACTO',
            field=models.ForeignKey(db_column='ID_CONTACTO', on_delete=django.db.models.deletion.CASCADE, to='main.Contacto'),
        ),
        migrations.AddField(
            model_name='apendicecabecera',
            name='ID_CONTRATO',
            field=models.ForeignKey(db_column='ID_CONTRATO', on_delete=django.db.models.deletion.CASCADE, to='main.ContratoCabecera'),
        ),
        migrations.AddField(
            model_name='apendicecabecera',
            name='ID_ESTADO',
            field=models.ForeignKey(db_column='ID_ESTADO', on_delete=django.db.models.deletion.CASCADE, to='main.Estado'),
        ),
        migrations.AddField(
            model_name='apendicecabecera',
            name='ID_VENDEDOR',
            field=models.ForeignKey(db_column='ID_VENDEDOR', on_delete=django.db.models.deletion.CASCADE, to='main.Vendedor'),
        ),
    ]
