# Generated by Django 2.2.3 on 2019-07-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsmodel',
            name='first_name',
            field=models.CharField(blank=True, help_text='first name', max_length=30),
        ),
        migrations.AlterField(
            model_name='contractsmodel',
            name='username',
            field=models.CharField(blank=True, help_text='username', max_length=150, unique=True),
        ),
    ]
