# Generated by Django 2.2.3 on 2019-07-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190725_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsmodel',
            name='first_name',
            field=models.CharField(blank=True, help_text='first name', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contractsmodel',
            name='username',
            field=models.CharField(blank=True, help_text='username', max_length=150, null=True, unique=True),
        ),
    ]
