# Generated by Django 2.2.3 on 2019-07-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190725_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsmodel',
            name='email',
            field=models.CharField(blank=True, help_text='email', max_length=254),
        ),
        migrations.AlterField(
            model_name='contractsmodel',
            name='first_name',
            field=models.CharField(blank=True, help_text='first name', max_length=30),
        ),
        migrations.AlterField(
            model_name='contractsmodel',
            name='last_name',
            field=models.CharField(blank=True, help_text='last name', max_length=150),
        ),
        migrations.AlterField(
            model_name='contractsmodel',
            name='username',
            field=models.CharField(blank=True, help_text='username', max_length=150, unique=True),
        ),
    ]
